services:
  mmamaritime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mmamaritime
    restart: unless-stopped
    env_file: .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "127.0.0.1:3006:3000"
    networks:
      - web

# Réseau partagé avec le reverse proxy Nginx global
networks:
  web:
    external: true
